volumes:
  postgres:

services:
  notebook:
    image: chris5896/data-mining-notebook 
    build: .
    ports:
     - 8888:8888
    volumes:
     - ./data:/home/jovyan/work
    restart: on-failure

  db:
    image: postgres:15
    restart: on-failure
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: datamining
      POSTGRES_PASSWORD: data-mining-123

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 4200:8080   
